version: 2
defaults: &defaults
  docker:
    - image: angular/ngcontainer:latest
  working_directory: ~/repo

jobs:
  # Build for all branches and tags
  build:
    <<: *defaults
    steps:
      # Checkout, Download and cache dependencies
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # Run the ci build
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test
      # Store artefacts on circle
      - run: mkdir -p /tmp/samples
      - run: cp -r --parents integration/samples/**/dist /tmp/samples
      - store_artifacts:
          path: /tmp/samples/integration/samples
          destination: samples
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - deploy:
          name: Deploy Git tag to npm registry
          command: |
            GIT_TAG=$(git tag -l --points-at HEAD)
            if [[ "${GIT_TAG}" =~ v([0-9]+)\.([0-9]+)\.([0-9]+)-([a-zA-Z]+)\..* ]]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              yarn publish:ci
              # Publish prerelease version with tag to npm registry
              pushd dist
              npm publish --tag next
              npm pack .
            elif [[ "${GIT_TAG}" =~ v.* ]]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              yarn publish:ci
              # Pack and publish latest version to npm registry
              push dist
              npm publish
              npm pack .
            fi

workflows:
  version: 2
  cirunner:
    jobs:
      - build:
          filters:
            branches:
              ignore: /gh-pages/
            tags:
              only: /v.*/
